### ISSUE TITLE
Rewrite Coordinate System

### ISSUE THREAD

**Issue by Shinmera** [Shirakumo/alloy#11]
The current coordinate system as employed in Alloy uses absolute positioning for everything. This has the immediate advantage that comparisons and resolution are free. Determining whether one geometry is within another requires no context query.

However, this brings with it some serious costs that I think are too big a burden to justify. Most notably, when a layout is moved, not only do its coordinates need to be updated, but also all of its children. This can incur significant cost, for something that could be almost free. This is especially damning in relatively common cases like scrollable lists.

In order to remedy this, a new protocol needs to be introduced that can be used to resolve geometries to absolute variants. We already need a system like this in order to resolve relative units to absolute ones, in particular ph/pw unit types, so an extension of that to allow transforming entire geometries would be good.

Things to consider here are:
- Should we only allow translation, or should rotations, skews, etc. also be allowed?
- We should probably cache the transform at each layout and update it whenever the layout is moved. That way resolving a child geometry only ever needs to consider the immediate parent rather than all ancestors.
- How do we perform geometry tests, most notably intersections?
- Currently the protocol that updates the bounds of an element will cause a relayout to happen. We need to prevent this unless it is absolutely necessary due to resizes... and possibly other actions?
- The renderers need to be updated to take the context into account.
- Switching the system to be 0,0 in topleft corner with y growing down, rather than the current bottomleft, y frowing up.

**Comment by Trashtalk217** [comment]
This sounds a lot like a graphics course I recently took. It focused on OpenGL, but I think it could be applicable here.

Maybe every layout-element could have a 3x3-matrix corresponding to its relative position to the origin of the container it's in. You wouldn't set this by hand, it would likely be done by the layout. To get the absolute value we could simply multiply the layout-element-matrix with the container-matrix and go up all the way to the root layout recursively. If you then change the position of the container you only have to update that matrix and it should still all work. 

The upside of this, is that you get any and all transformation for free, given that the renderer supports this. It would also be somewhat easy to write the renderer, as OpenGL is basically built to facilitate this.

A major downside is that you can't enforce constrictions as easely. e.g: These buttons should be two pixels apart.

For intersection calculations you could maybe take a look at bounding boxes. This is another problem programmers, and more specifically, people making games have optimized to Tokyo and beyond before I was born.

**Comment by Shinmera** [comment]
Sure, if you want full 2D transforms you'd use a 3x3 transforms matrix. The simple renderer protocol [already employs this](https://github.com/Shirakumo/alloy/blob/master/renderers/simple/transforms.lisp).

If you only want translation, then you only need a 2d vector addition, though. It would also lessen the burden on the renderer. For instance, I don't think most UI toolkits allow rotating or skewing components, which would make creating a backend using them difficult

**Comment by Trashtalk217** [comment]
I'll agree with you on that, while you could do al sorts of transformation, scaling and translations are the only usefull ones. I didn't know that simple already employs this render method, I should've looked first. It's always ensuring to know that my university eductation has uses.

What about scaling by the way? It's not in the list of transformations in your question.

**Comment by Shinmera** [comment]
Scaling is why I had the "etc" there :)

It's also not entirely true to say that scale and translate are the only useful ones. Rotation can also be useful at times if you would like to do something like a radial or fan menu. The only affine transformation I can't see a use for would be skew. In any case, the question here is less about what would be useful, and more about what kinds of concessions should be made for the protocol.

There's essentially the following possibilities:
1. Restrict ourselves to translation and scaling to ensure every backend can support the full feature set. This would mean making certain UIs impossible without special components that make use of backend-specific extensions, and such extensions would almost definitely be messy.
2. Allow full affine transforms, but allow backends to only support a subset. This would mean that some UIs will not work as expected with some backends.
3. Allow full affine transforms and force backends to support the full set. This would mean some backends would not be able to offer native components in all situations and would require significant effort to emulate components in cases where they cannot be done natively.

**Comment by Shinmera** [comment]
Also interesting to consider would be allowing arbitrary shapes for layout elements, rather than requiring them to be box geometries. Especially things like fan menus or very stylised UIs would require that kind of thing to be supported at the layout level in order to allow the pointer event propagation to function properly.

**Comment by Trashtalk217** [comment]
It depends on how extra you want the protocol to be. I personally prefer the simplest protocol, to start with: only translation and scaling and only rectangles. I'd then find workarounds for things like: [pie menus](https://en.wikipedia.org/wiki/Pie_menu) and [fan menus](https://github.com/exyte/fan-menu).

(key takeaway from those two components is that circles are the future, apparently)

It would probably be ideal to give users some functionality to add these things in themselves, but that can quickly get out of hand and it's nice to have a UI toolkit that just works out of the box and you don't have to have an extra system (e.g. `alloy-addons`).

**Comment by Shinmera** [comment]
Relative positioning was merged a while ago.
