### ISSUE TITLE
Joining cells in grid-layout (feature request)

### ISSUE THREAD

**Issue by Trashtalk217** [Shirakumo/alloy#15]
I've been playing around with the grid-layout to try and make a calculator and I've ran into something the toolkit is missing. I'd like to have a layout-element spanning multiple cells. I've been trying to think this through and I've been reading the grid-layout code, but I don't see a simple solution. My first idea was to have the array that stores the layout-elements be allowed to have copies which are deconstructed later into full elements. I'm wording this badly, but an example will show it better:
```
[ A, A, A, A
  B, C, D, E,
  F, F, G, H,
  F, F, I, J ]
```
But it seems that I can only have a layout-element once in the grid-layout, so this isn't going to fly.

I want to add this feature myself, but I would like some pointers on how to approach this problem. Any help would be appreciated.

**Comment by Trashtalk217** [comment]
#16

**Comment by Shinmera** [comment]
A `grid-bag-layout` has been implemented by @scymtym
