### ISSUE TITLE
System "sdf/bmfont" not found

### ISSUE THREAD

**Issue by aymanosman** [Shirakumo/alloy#19]
I got the above error when trying to install the `alloy-opengl-msdf`system.

**Comment by tgbugs** [comment]
Same issue. Amusingly I started the day looking into signed distance fields for fonts in cl, and wound up here more or less by accident.

**Comment by Shinmera** [comment]
https://github.com/3b/sdf branch msdf. 

Note though that the msdf backend is currently pretty broken unless font atlases are generated with an external tool like https://github.com/soimy/msdf-bmfont-xml . @3b has been working on a newer version of the generator that should work on any font file and glyph, but it isn't done yet.

**Comment by aymanosman** [comment]
Thanks, that got things compiling.

P.S. I ran into this while trying to run the kandria project on my mac. I got everything compiling (after a small change to the the `<trial>/harmony/asset.lisp` file). Couldn't get the game running though with `kandria:launch`. Not even sure it's reasonable to expect to be able to run it :).

**Comment by Shinmera** [comment]
The kandria sources on github are not up to date and I can't offer support for them I'm afraid.
