### ISSUE TITLE
Instructions on getting sdf/bmfont is not very clear...

### ISSUE THREAD

**Issue by Inc0n** [Shirakumo/alloy#22]
As it turns out, this specific branch is needed https://github.com/Shinmera/sdf/tree/msdf.

Well, ultimatley I want this issue to be found by others who intend to give alloy a try and help them to get started with alloy-glfw.

**Comment by Shinmera** [comment]
It is recommended to use the https://dist.shirakumo.org/shirakumo dist to fetch the required dependencies.
