### ISSUE TITLE
Alloy on Mac Osx

### ISSUE THREAD

**Issue by Inc0n** [Shirakumo/alloy#23]
The example on glfw, doesn't even start an window... Perhaps alloy is not supported on Mac Osx, for some reasons?
There is no error either. But cl-glfw3 is fine, the example basic-window ran fine.

**Comment by Shinmera** [comment]
Did you run things from the main thread, ie, without slime? Mac in general has issues with main-threadiness.

**Comment by Inc0n** [comment]
No, unfortunately I ran it within slime.

**Comment by Shinmera** [comment]
You might be able to run sbcl from the terminal, then start swank later and avoid the issue that way. I don't remember what magic incantations are required these days, and honestly ran out of patience dealing with Apple's bs years ago.

**Comment by Inc0n** [comment]
Very true indeed, I regretted a long time ago after acquiring this m1, *sigh*

**Comment by Shinmera** [comment]
In any case, main-threadness aside, Alloy does work on MacOS. There's no other platform dependent stuff in it, anyhow.

**Comment by Inc0n** [comment]
Okay, with thread out of the way.... now when I run it, it flashes a very small window (presumably because I didn't set window height or width), and disappears very quickly. There is no substantial output from the slime repl that suggests anything related to this behaviour.

**Comment by Shinmera** [comment]
Did you try any of the examples, or?

**Comment by Inc0n** [comment]
I was trying combo from https://github.com/Shirakumo/alloy/blob/master/examples/windows.lisp. Also the example you gave me while back: https://github.com/Shirakumo/alloy/issues/1#issuecomment-611354210.
Both have the same behaviour.

**Comment by Shinmera** [comment]
Odd. The examples work fine on Linux and Windows.

**Comment by Inc0n** [comment]
*Sigh* just not on macs or because of something from my personal setup, I don't know for sure which.

**Comment by Shinmera** [comment]
I'm afraid I don't know any more than you. As I said, I haven't tested on mac in years. Last I tried a Kandria build on it all the UI bits (which are all Alloy) did work. I imagine this is some minor problem in the alloy-glfw backend or something.
