### ISSUE TITLE
[Discussion] Observing leave/parent leave events.

### ISSUE THREAD

**Issue by bmiww** [Shirakumo/alloy#35]
Want to bounce an idea at you.

I want to associate buttons/clickable elements with dedicated keyboard keys for them.
The first thought i had when i started going into that direction was - i'm going to initialize a component that will subscribe to a leave/enter event (of the component itself and its parents).

Would you imagine any immediate problems with turning all container/element classes observable?

Was thinking about how component/layout parents could notify their leave/enter events, and thought that the least performance impact could possibly be - setting up an observation on the leave event on a component of interest could iterate upwards creating an observation in all parents that would notify the initial child of interest when they've left. Possibly via specialized event rather than leave? Since it might then be of interest to have the event signature more along the lines of:
```
(alloy:on alloy:something-in-tree-left (observable-of-interest observable-that-left-their-parent parent-that-was-left)
  (handle))
```

As is currently - i could probably handle these things on a different level, but somehow am stuck on the idea, and wanted to test the waters.

**Comment by Shinmera** [comment]
In my experience this kind of thing is extremely brittle. For instance: what should happen if an entire subtree, rather than an individual leaf is added or removed?

Since what you're looking for is essentially a global registry, I think it would be more reasonable to add a table to the `ui` object that connects keyboard accelerators to an action that should be triggered on a particular element. The element can then de/register itself with a method on `set-focus-tree`, as the protocol guarantees that this is called for every element of any sub-tree already.

**Comment by bmiww** [comment]
Ahaa, did not notice set-focus-tree.
Yeah, global registry is what i was going for anyways - was missing the event to associate the change with.
I think set-focus-tree will do nicely.

Was overly **focused** on the layout components to notice :)

On the idea i wrote of itself - perhaps am prematurely optimising, but still wanted to explore the thought.
Imagined a tree with a 1000 leaves, while im perhaps only interested in referencing one when its ancestors leave. In which case - top-down would mean iterating over 1000 things.

To answer the example you gave - was imagining that the leave/enter events themselves would propagate upwards any observations of children that are interested in observing their ancestry. Aka - subtree leaves - ancestors of that subtree each loses the observers from that subtree. Subtree gains a new parent - the whole new ancestry gets notified that something is interested in their leave/enter events. Basically elements would know that some child somewhere has interest, and that this interest should be made known to the direct parent - repeat.

Any case, thanks for the pointer to set-focus-tree. With it available, i dont think i'll manage to keep my interest in this idea for too long anyways, so i'll close this up.
