### ISSUE TITLE
sliders loses focus while adjusting if mouse move out of the slider

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [Shirakumo/alloy#4]
While unfocused the components gain focus correctly corresponding to the mouse movements.

However, the components focused, slider in this case, will loses focus if mouse moves out of the component region. 

The current behaviour can be reproduced with the example code you given me in this issue.
https://github.com/Shirakumo/alloy/issues/1#issuecomment-611354210

It will be better if the currently interacted components will not lose focus when mouse move out of it.

**Comment by Shinmera** [comment]
I did write logic to handle this, but it probably broke at some point.

Focus right now is busted anyway, several invariants are not upheld.

**Comment by Inc0ns1st3nt** [comment]
> I did write logic to handle this, but it probably broke at some point.

could you tell me which files to look into

> several invariants are not upheld.
What do you mean by that?

**Comment by Shinmera** [comment]
Should all be contained in `components/slider.lisp`

As for the invariant, see the [logs](https://irclog.tymoon.eu/freenode/%23shirakumo?around=1588433407#1588433407)

**Comment by Inc0ns1st3nt** [comment]
ahh i see thanks!

**Comment by Inc0ns1st3nt** [comment]
Hi it seems that the focus system works as intended:
> all ancestors of a strongly focused element must be weakly focused. only one immediate child of a strongly focused element may be weakly focused. any other element must be unfocused.

The currently dragging slider will loses focus regardless of its state, and the focus will be given to the component under the mouse.

And to fix this, I would suggest to perhaps implement a new generic method for `focus-element` that is called whenever an element is going to lose focus, which by default will return `t`, indicate by default it gives up the focus. However, if under any other conditions that this element should not give up focus, it should override this method and return `nil`.

Would this be a reasonable fix for this issue?

**Comment by Shinmera** [comment]
It does not work as intended. It might in this case, but there are severe bugs about it around still.

There is no need to add additional functions. In order to allow this behaviour, the system is intended to proceed as follows: pointer events are first sent to the currently focused element. If this element declines to handle it, it is then sent to the root element, and bubbles upwards in the hierarchy. This should allow the currently focused element to capture pointer events outside of its region.

I'm not sure what part of that is broken now, but it did work properly like that at one point.

**Comment by Inc0ns1st3nt** [comment]
Some behaviour I observed: After commenting out `(call-next-method)` in `handle` for its `T` case

**Comment by Shinmera** [comment]
The problem was indeed elsewhere, the GLFW backend did not follow the event protocol correctly.
