### ISSUE TITLE
Problems when attempting to try alloy-examples

### ISSUE THREAD

**Issue by defaultxr** [Shirakumo/alloy#41]
Hi.

After installing the Shirakumo quicklisp dist, I tried to quickload alloy-examples and I got errors for the `framebuffers` and `raster` systems not existing. I was able to manually clone those into my local-projects, though, and alloy-examples loaded fine afterwards. Not sure if those are intentionally excluded from the dist at this moment.

After that, I get the following error when I try running either `(org.shirakumo.alloy.examples:grid-bag-layout)` or `(org.shirakumo.alloy.examples:sizing)`:

```
Invalid initialization argument:
  :PREFERRED-SIZE
in call for class #<STANDARD-CLASS ORG.SHIRAKUMO.ALLOY.RENDERERS.FRAMEBUFFERS:WINDOW>.
   [Condition of type SB-PCL::INITARG-ERROR]

Restarts:
 0: [RETRY] Retry SLY mREPL evaluation request.
 1: [*ABORT] Return to SLY's top level.
 2: [ABORT] abort thread (#<THREAD tid=1532617 "sly-channel-1-mrepl-remote-1" RUNNING {1000A78893}>)

Backtrace:
 0: (SB-PCL::INITARG-ERROR #<STANDARD-CLASS ORG.SHIRAKUMO.ALLOY.RENDERERS.FRAMEBUFFERS:WINDOW> (:PREFERRED-SIZE))
 1: ((:METHOD MAKE-INSTANCE (CLASS)) #<STANDARD-CLASS ORG.SHIRAKUMO.ALLOY.RENDERERS.FRAMEBUFFERS:WINDOW> :SCREEN #<ORG.SHIRAKUMO.ALLOY.EXAMPLES::SCREEN {1008ECB533}> :PREFERRED-SIZE (ORG.SHIRAKUMO.ALLOY:S..
 2: ((FLET "THUNK0" :IN ORG.SHIRAKUMO.ALLOY.EXAMPLES:GRID-BAG-LAYOUT) #<ORG.SHIRAKUMO.ALLOY.EXAMPLES::SCREEN {1008ECB533}>)
 3: (ORG.SHIRAKUMO.ALLOY.EXAMPLES:GRID-BAG-LAYOUT)
 4: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ORG.SHIRAKUMO.ALLOY.EXAMPLES:GRID-BAG-LAYOUT) #<NULL-LEXENV>)
 5: (EVAL (ORG.SHIRAKUMO.ALLOY.EXAMPLES:GRID-BAG-LAYOUT))
```

I tried to update the dist just in case but it says it's already up to date.

`(org.shirakumo.alloy.examples:fonts)` and `(org.shirakumo.alloy.examples:simple-window)` both run fine though, and start a window (though it doesn't show anything other than solid black).

If it matters, I'm running the examples under X on Linux with an AMD GPU.

I know Alloy's version is still 0.0.0, so maybe it's not meant for general use at the moment, but I figured I would let you know about the issues I ran into anyway just in case.

**Comment by Shinmera** [comment]
Looks like I pushed a bad commit. The examples aren't meant to use the framebuffers backend yet, since it's far from done in any capacity. I pushed a fix to use the intended alloy-glfw backend instead.

**Comment by defaultxr** [comment]
After cloning alloy from git master I'm seeing that the examples are indeed all working now and displaying the window contents. Thanks!
