### ISSUE TITLE
System "colored" not found

### ISSUE THREAD

**Issue by Trashtalk217** [Shirakumo/alloy#6]
I'm looking to help with the development of Alloy in the summer and I'm trying to get my barrings in this codebase. When trying to set up Alloy, I wanted to take a look in the example directory. But when trying to `CL-USER> (ql:quickload :alloy-examples)` the system I got the following error:

```
System "colored" not found
   [Condition of type QUICKLISP-CLIENT:SYSTEM-NOT-FOUND]
```
What do I do about it and do you have any advice for prodding around in the project?

**Comment by Shinmera** [comment]
First of all, thank you very much for your interest in the project! Feel free to also hop on by our channel #shirakumo on Freenode for more immediate contact.

As for colored, that's here: https://github.com/shinmera/colored 
I haven't gotten around to finalising and documenting it, which is why it's not on quicklisp yet. I should really get around to that...

**Comment by Shinmera** [comment]
As for prodding around:

- Make sure to read what's there of the documentation on the overall concepts
- Read the TODO.mess file for possible larger tasks to tackle
- Use something like magit-todos to scan the projects for TODO/FIXME/KLUDGE lines and see if there's anything that you think you could tackle
- Try to write a simple application with Alloy and see how far you can get

For any problems or questions I'd be more than happy to help out!

**Comment by Trashtalk217** [comment]
Thank you for the quick reply, I'll be busy prodding for probably the next week, maybe then I can start fixing some small things here and there. Is there any other way I can talk to you? Communication via issues is probably not preferable (at least not for me anyway).

**Comment by Shinmera** [comment]
As mentioned, the IRC channel #shirakumo on Freenode is probably the best way. There's other interested people there and having more active discussion might invite more interest too :)

**Comment by Trashtalk217** [comment]
My impatience has once again led me to forget reading important information. I'm sorry, I'll speak to you on Freenode.

**Comment by Shinmera** [comment]
No problem, haha! See you there.

**Comment by Shinmera** [comment]
Cf quicklisp/quicklisp-projects#1866
