### ISSUE TITLE
Combo rendering not working well

### ISSUE THREAD

**Issue by Trashtalk217** [Shirakumo/alloy#7]
All of the issues below have been found by testing the combo function in the alloy-examples package.

I've been testing out the software for the last few days and noticed the following two things. The combo doesn't correctly overlay the rest of the UI: [example](https://i.imgur.com/h43HfdG.png)

It's also possible to select the value NIL even thought that's not in the options list: [example-2-electric-boogalo](https://i.imgur.com/h2PhmRv.png)
This can be reproduced by double clicking the box that opens the drop-down.

Also another minor nit-pick, what is currently called a combo-box in the code is actually a drop-down. A combo-box usually has a search function: [Wikipedia](https://en.wikipedia.org/wiki/Combo_box)

**Comment by Shinmera** [comment]
I think the overlapping is a problem with the renderer's z-sorting.

Also, it is a combo-box, just not a combination of a search field and drop down, but a button and a drop down.

**Comment by Trashtalk217** [comment]
Would it be handy for a combo box to have a default value as in:
`(combo (alloy:represent selection 'alloy:combo-set :value-set '(:a :b :c) :default :foo)))`
to fill the box with when nothing is explicitly chosen? When no `:default` is supplied the box stays empty.

**Comment by Shinmera** [comment]
The "default" is whatever the data is set to when you represent it. So in your case, make sure `selection` is set to an actual element that's part of the value-set.

**Comment by Shinmera** [comment]
Having the combo be a search field to trim down on possible entries in the set would be very good though. Just not sure how to go about it yet.

**Comment by Trashtalk217** [comment]
There are definitely a lot of "modern" UI components that would be nice to have. From elements as small as chips to things as big as date selectors.

**Comment by Shinmera** [comment]
Stuff like a date selector, and arguably the combo, too, should rather be structures than components. So far I've intended on keeping components as minimal as possible, and instead making everything else a structure -- a combination of layouts and components.

That part of Alloy needs some rethinking, though.
